### ISSUE TITLE
Missing CorrelationID

### ISSUE THREAD

**Issue by snacloudservices** [singer-io/tap-exacttarget#2]
The CorrelationID is missing from this setup.  Without it, I'm not able to relate emails to their respective campaign.  

Could the CorrelationID be added to the configuration?

**Comment by snacloudservices** [comment]
The CorrelationID is part of the SOAP request which this is referencing in the readme but the code is calling the REST endpoint https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/getCampaign.htm

**Comment by nick-mccoy** [comment]
Hey @cmcarthur, looks like this tap's README references the SOAP docs even though it is using the REST API.  

I can create a PR to fix it, I just wanted to make sure the choice to reference the SOAP docs wasn't intentional.

**Comment by nick-mccoy** [comment]
@cmcarthur Is there any way to figure out which API FuelSDK is calling out to?  I don't want to change all the links to reference the REST docs if some of the streams use the SOAP API.  I guess I can go stream-by-stream and check out the response if you're not sure.

**Comment by cmcarthur** [comment]
@nick-mccoy I don't know if there's documentation anywhere for it. I figured this out from reading the FuelSDK code :( I may have time later this week to go through it again and figure out which are REST

**Comment by nick-mccoy** [comment]
@cmcarthur I looked at the FuelSDK code, and traced the base classes for the objects.  From what I can tell:
- Campaigns inherits from FuelSDK.rest.ET_GetSupportRest
- Everything else inherits from FuelSDK.rest.ET_GetSupport

I _think_ this means that Campaigns is the only stream using the REST API, and everything else uses SOAP?

**Comment by snacloudservices** [comment]
Any thoughts on how we can get relate the campaigns to their respective emails?

**Comment by nick-mccoy** [comment]
Without the correlationID, I don't see a clear way to link the two.  You could try reaching out to the singer community to see if anyone there has any ideas.  

I'm going to close this issue, though.

**Comment by snacloudservices** [comment]
To associate the campaign id with the email you would need to look at the associate assets to campaign page.
https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/associateAssetToCampaign.htm

Or for each campaign you could get the collection of campaign assets
https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/getCampaignAssetCollection.htm
