### ISSUE TITLE
Synching error in 'Events' table

### ISSUE THREAD

**Issue by alvindang21** [singer-io/tap-exacttarget#26]
Unable to synchronize remaining records in **Event** table, following error blocks and persists:

`Error persisting data for table "event": Record is missing key property SubscriberKey`

It's not possible to have a record in any of the separate event tables without a SubscriberKey.

Any thoughts?

**Comment by cosmok** [comment]
I am encountering the same error.

**Comment by cosmok** [comment]
Strangely, there are no nulls:


SELECT  TOP 100 "SubscriberId", "SubscriberKey", "EventDate", "BatchID", '_sent' AS "table" FROM _Sent WHERE Len((SubscriberKey)) < 1 OR  SubscriberKey = NULL
UNION
SELECT  TOP 100  "SubscriberId", "SubscriberKey","EventDate", "BatchID", '_open' AS "table" FROM _Open WHERE Len((SubscriberKey)) < 1 OR  SubscriberKey = NULL
UNION
SELECT  TOP 100 "SubscriberId", "SubscriberKey","EventDate", "BatchID",  '_click' AS "table" FROM _click WHERE Len((SubscriberKey)) < 1 OR  SubscriberKey = NULL
UNION
SELECT  TOP 100  "SubscriberId", "SubscriberKey","EventDate", "BatchID",  '_unsubcribes' AS "table" FROM _unsubscribe WHERE Len((SubscriberKey)) < 1 OR  SubscriberKey = NULL
UNION
SELECT  TOP 100 "SubscriberId", "SubscriberKey","EventDate", "BatchID",   '_bounce' AS "table" FROM _bounce WHERE Len((SubscriberKey)) < 1 OR  SubscriberKey = NULL

is empty

**Comment by rdeshmukh15** [comment]
Closing as the fix is provided and merged to master
