### ISSUE TITLE
No data subscriber SalesForce Marketing cloud (stitchdata)

### ISSUE THREAD

**Issue by elogia** [singer-io/tap-exacttarget#51]
Hi!

I can't get the data from the subscribers table, or list_suscribers. I understand that it is because there are fields that have "null" data. How can I solve it?

Use stitchdata
Thank you!

I attach a log :)

**Comment by Vi6hal** [comment]
@elogia need more details on this, would be happy to help.
not able to find the log attached.
as issue is very old closing it, please reopen with the details.
