### ISSUE TITLE
Not marked selected...

### ISSUE THREAD

**Issue by igamezrim** [singer-io/tap-exacttarget#57]
When I run tap-exacttarget -c config.json --properties catalog.json, I got this.
pleas help me.

INFO 'campaign' is not marked selected, skipping.
INFO 'content_area' is not marked selected, skipping.
INFO 'data_extension.RCM_DemoBday' is not marked selected, skipping.
INFO 'data_extension.Eesh Test - 20190514_045659' is not marked selected, skipping.
INFO 'data_extension.TriggeredSendDataExtension - 20190514_065934' is not marked selected, skipping.
INFO 'data_extension.Segment_PR' is not marked selected, skipping.
INFO 'data_extension.W85_Openers' is not marked selected, skipping.
INFO 'data_extension.asali_merkleinc_com - 20190611_022640' is not marked selected, skipping.
INFO 'data_extension.Eesh Test - 20190611_061944' is not marked selected, skipping.
INFO 'data_extension.test1234' is not marked selected, skipping.
INFO 'data_extension.X_Openers' is not marked selected, skipping.

**Comment by iBluday** [comment]
Same too here. please help me.
