### ISSUE TITLE
tap - WARNING No import token found for connection

### ISSUE THREAD

**Issue by afialk** [singer-io/tap-exacttarget#95]
Hey team,

Our Stitch connector has worked well for many years now, but an error/warning combination arose on 1/17 that's preventing any data from being moved to our Snowflake data warehouse from SFMC.

Immediately upon extracting, we get a message saying, "main - WARNING No import token found for connection." That recurs through out the logs. The process then seems to successfully retrieve rows from the DataExtension field endpoint before ending in a terminal error, "main - CRITICAL Error saving list of discovered streams: {'message': 'Not Authorized'}."

We checked several possible sources for this—our SFMC credentials our valid, and our Snowflake permissions are unchanged. I also simply cloned the Integration, and that wrote to a new schema successfully, without changes. Do you have any thoughts about what could cause this, or suggestions for further troubleshooting? We could of course use the cloned version, though I'd prefer to avoid updating all the views that reference the previous schema, if possible.

Thanks!

**Comment by Vi6hal** [comment]
Hello @afialk , Thank you for reporting this issue.
I would suggest you to start a conversation with stitch support team stating the above issue and sharing the relevant details such as connection name , id etc..
(you can find a chatbox on the lower right corner of the screen after opening the stitch web app)

Thanks.
